language: python

#which versions of python to test against
python:
  - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip install codecov
  - pip install coverage

script: 
  - python -m unittest discover -v ./ # command to run unit test
  - coverage run ./test.py # command to run code coverage
  
after_success:
 - codecov --token=$COV_TOKEN # upload coverage report to codecov.io
 
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:  $AWS_SECRET_ACCESS_KEY
  bucket: cps847-3271
  local-dir: dat.html
  region: $AWS_DEFAULT_REGION
  skip_cleanup: true
  acl: public_read
