language: python

#which versions of python to test against
python:
  - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip install codecov
  - pip install coverage

script: 
  - python -m unittest discover -v ./ # command to run unit test
  - coverage run ./test.py # command to run code coverage
  
after_success:
 - codecov --token=$COV_TOKEN # upload coverage report to codecov.io
